--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/UIPlugins/EvalUI
branches:
- master
projects:
  EvalUI:
    path: ""
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^1.3
...