name: EvalUI
main: ARTulloss\EvalUI\EvalUI
api: [3.2.0]
version: 1.0.1
author: ARTulloss
description: We needed this too

permissions:
  eval:
    description: Eval as a UI!
    default: true # Change this to false or op if production, otherwise you're good to go!